### ISSUE TITLE
Suggested changes to text of JOSS paper

### ISSUE THREAD

**Issue by matt-graham** [kazewong/flowMC#82]
Raising issue as part of JOSS review https://github.com/openjournals/joss-reviews/issues/5021

Some suggested changes to the text of the JOSS paper:

_However the estimation of models'parameters_ &rightarrow;  
_However the estimation of models' parameters_  
(missing space between models' and parameters)

_A common strategy to explore parameter space is to sample through a Markov Chain Monte Carlo (MCMC)._ &rightarrow;  
_A common strategy to explore **a model's** parameter space is **to approximately sample the posterior distribution on the parameters with a** Markov Chain Monte Carlo (MCMC) **method**._  
(Markov chain Monte Carlo is a descriptor of a class of algorithms and wouldn't usually be used as an object grammatically; MCMC methods sample from a distribution so helpful to specify what distribution this is)

_Yet even MCMC methods can struggle to faithfully represent the parameter space when only relying on local updates._ &rightarrow;  
_Yet even MCMC methods can struggle to faithfully represent **the posterior distribution on** the parameter space when only relying on local updates._  
(the Markov chain samples generated by an MCMC method represent a distribution on the parameter space, typically a posterior distribution in a Bayesian inference context, not the parameter space itself)

_FlowMC is a Python library for accelerated Markov Chain Monte Carlo (MCMC)_ &rightarrow;  
_FlowMC is a Python library implementing accelerated MCMC [methods/algorithms]_  
(no need to repeat acronym definition and again better to use MCMC as a qualifier)

_At its core, FlowMC uses a local sampler and a learnable global sampler in tandem to efficiently sample posterior distributions_ &rightarrow;  
_At its core, FlowMC combines Metropolis-Hastings based Markov kernels proposing local moves and global moves (using a learned approximation to the target distribution) to efficiently sample posterior distributions with non-trivial geometry_  
(to me local and global sampler are too vague and in particular _global sampler_ is a bit misleading as the moves proposed using the normalizing flow model are still accepted or rejected within a Metropolis acceptance step meaning the moves are still 'local' when the proposals are rejected)

_While multiple chains of the local sampler generate samples over the region of interest in the target parameter space, the package uses these samples to train a normalizing flow model, then use it to propose global jumps across the parameter space._ &rightarrow;  
_While multiple chains using Markov kernels with local moves generate approximate samples from the target posterior distribution on the parameter space, the package uses these samples to train a normalizing flow model approximating the target distribution, and uses this approximation to propose global jumps across the parameter space within a Metropolis independence sampler._

_MALA_ &rightarrow; _Metropolis adjusted Langevin algorithm (MALA)_  
_GPUs_ &rightarrow; _graphics processing units (GPUs)_   
_TPUs_ &rightarrow; _tensor processing units (TPUs)_  
_SIMD_ &rightarrow; _single instruction multiple data (SIMD)_
(all abbreviations should be defined on first usage)

_As soon as the dimension of  exceeds 3 or 4, it is necessary to resort to a robust sampling strategy such as a MCMC_ 

I would not be so specific here as actually I would say MCMC methods are not necessarily the best choice for target distributions on spaces with dimension 5 with quadrature methods, rejection sampling and importance sampling methods all being potentially viable in these sort of dimensionalities. I would say something more vague like _In high dimensions_ or _For parameters spaces with more than a few dimensions_ would be better.

_`Jax`_ &rightarrow; _`JAX`_ (capitalisation should be consistent throughout)

_GPU and TPU supports_ &rightarrow; _GPU and TPU support_

_The entire algorithm belongs to the class of adaptive MCMCs_ &rightarrow; _The entire algorithm belongs to the class of adaptive MCMC methods_

_the chains previous steps_ &rightarrow; _the chains' previous steps_

_Use of Accelerator_ &rightarrow; _Use of Accelerators_

_leverage Just-In-Time_ &rightarrow; _leverage JIT_ (abbreviation has been previously defined so should be used for subsequent usages)

_the log-posterior function_ &rightarrow; _a function to evaluate the logarithm of the (unnormalized) density of the posterior distribution of interest_

**Comment by Daniel-Dodd** [comment]
Comments on the paper as part of JOSS review https://github.com/openjournals/joss-reviews/issues/5021, to supplement the (excellent) review above. **NOTE** these comments with regards to commit; d2414382fd74d51ed6d8ad9b9c28dd67e0592865, on kazewong/flowMC/40-joss-paper, which is currently the latest version of the paper.

# General typo comments (in addition to the above review):

- [ ] **Title:** Normalizing flow should not have a hyphen.
- [ ] **Capitalisation:** unless, it is the first word of a sentence, or is someones name, e.g. Markov or Bayesian, do not capitalise. For example,  *`Just-In-Time` to `just-in-time` , or* `Markov Chain Monte Carlo` to `Markov chain Monte Carlo` , or `Rational-Quadratic Splines` to `rational quadratic splines` (there is no hyphen here), … etc.
- [ ] As mentioned by the other reviewer. All acronyms need to be defined on first usage, but do not need to be repeated again. Another one not given above is `HMC` as `Hamiltonian Monte Carlo` .
- [ ] You are using NF, short for, normalising flow. This is fine, but I would recommend defining this upon the first instance of normalizing flow appears (which is the _summary_ section) and using NF thereon.
- [ ] None of your math equations are correctly punctuated.
- [ ] Remove unnecessary adjectives from the manuscript. These make sentences challenging to read, e.g. `more and more` , `increasingly` , `very` , etc.

From [](https://github.com/matt-graham)the other reviewer’ feedback in the above, I would recommend you hyphenate `Metropolis-adjusted Langevin algorithm (MALA)` , and do not capitalise “chain” in `Markov chain Monte Carlo`.

For more typos please see my PR #80. Note this PR does not address all the above (or the below), it only contains some of what I have noticed.

# Structure (mostly ignoring typos here)

## Summary

_“Across scientific fields, more and more flexible models are required to understand increasingly complex physical processes.”_ 

- [ ] Baseless claim. Need examples with citations if you wish to use this in the paper.

_“However the estimation of models’parameters becomes more challenging as the dimension of the parameter space grows.”_

- [ ] Motivate why we need high dimensional probabilistic models to model physical processes in the first place? Why does inference become challenging in higher dimensions? 

_“estimation of models’parameters”?_ This is myopic for a Bayesian approach? I would talk about the challenges of inferring the posterior distribution, rather than parameter estimation (which is only one facet of Bayesian inference).

- [ ] Perhaps mention intractability of the posterior and would motivate why we are using approximate inference to begin with? 

typo: _`models’parameters`_

_“*Yet even MCMC methods can struggle to faithfully represent the parameter space when only relying on local updates.”*_

- [ ] What MCMC methods? Perhaps you mean `conventional` MCMC methods? Please say so.
- [ ] Why / in what sense do they struggle? Perhaps you mean they are inefficient / take longer time to converge in higher dimensions. Can you please reference literature that highlights this issue.
- [ ] As identified by the first reviewer, parameter space is another typo.

_“The flowMCsampler can handle non-trivial geometry, such as multimodal distributions and distributions with local correlations.”_

- [ ] typo: _`flowMCsampler`_

“It is built on top of the machine learning libraries JAX and Flax.” 

- [ ] Both JAX and Flax need citations.

_“While multiple chains of the local sampler generate samples over the region of interest in the target parameter space, the package uses these samples to train a normalizing flow model, then use it to propose global jumps across the parameter space.”_

- [ ]  _“the package”_ I would be specific with `flowMC`

_“The key features of flowMC are summarized in the following list:”_

- [ ] Personally, not a fan of seeing bullet lists in a paper. This could be rewritten more cohesively.

I would try and aim for two concise paragraphs at the most in this section. Though you do state some features of normalising flow enhanced MCMC, I would tell the story in a differently to make the comparison clearer to why you would use this over conventional MCMC. I would first be specific with the misgivings  of conventional MCMC, i.e., inefficient in high dimensions, state the issues with multimodal and locally correlated distributions, and then after that introduce the normalising flow approach “on the other hand” …. Perhaps mention the target audience, to draw reader in.


## Statement of need

Already mentioned. But it is important you punctuate all maths.  

***Gradient-based sampler***

_“The computational cost of obtaining a gradient in this way is often of the same order as evaluating the target function itself, making gradient-based samplers favorable with respect to the efficiency/accuracy trade-off.”_

- [ ] This is a baseless claim. Moreover, it is irrelevant if this is generally true for most automatic differentiation software. What is of relevance here: can you guarantee this true specifically for your JAX implementation, and or for JAX in general? If yes, do justify, if not then remove. This otherwise serves as an unfounded performance claim, and I advise you remove this.

**Learned transition kernels with normalizing flow**

_”Posterior distribution of many real-world problems have non-trivial geometry such as multi-modality and local correlations, which could drastically slow down the convergence of the sampler only based on gradient information.”_

- [ ] Baseless claim. Please cite relevant literature.

- [ ] Typo: _“Variant of this idea have been...”_ to _“Variant**s** of this idea have been...”_

- [ ] _“and references therein”_. If these are important, please cite, if not remove.

- [ ] _`Sequential Monte Carlo`_ to _`sequential Monte Carlo`_

- [ ] ***`Use of Accelerator`*** to ***`Use of accelerator`***
 _”Modern accelerators such as GPUs and TPUs are designed to execute dense computation in parallel. Due to the sequential nature of MCMC, a common approach in leveraging accelerators is to run multiple chains in parallel, then combine their results to obtain the posterior distribution. However, a large portion of the computation time comes from the burn-in phase for which chain-parallelization provides no speed up.”_

- [ ] Don’t see how this is relevant. I would remove this, to just have just this:

_`flowMC` is built on top of `JAX`, so that it supports the use of GPU and TPU accelerators by default. Users can write codes in the same way as they would do on a CPU, and the library will automatically detect the available accelerators and use them at run time. Furthermore, the library leverage Just-In-Time compilations to further improve the performance of the sampler._

- [ ] Note there are a few typos in the above paragraph as identified in my PR #80.

_**Simplicity and extensibility -**_ Make it clear this concerns the target audience.

_“While we provide a high-level API for most of the users, the code is also designed to be
extensible.”_

- [ ] Who are “most of the users”? Practitioners?
- [ ] Designed to be “extensible”.  Great, but for whom? Researchers?
- [ ] Make it clear who the target audience is.

# Overall

This is shaping up nicely. You give key functionality that your library has to offer and identify the advantages of a JAX codebase. Just need to fix those typos, and support some the claims made. Look forward to reading the revised version. :)

**Comment by marylou-gabrie** [comment]
Thanks a lot @Daniel-Dodd and @matt-graham for the valuable feedback and the spotted typos.

I iterated on your suggestions in commit:
[#1827618](https://github.com/kazewong/flowMC/commit/1827618fdd86b50c94b18b1a210e508a83d18a21)

@Daniel-Dodd we are leaning towards keeping the key features itemized as we feel it makes it easy for readers to parse them.

**Comment by Daniel-Dodd** [comment]
Nice work, @marylou-gabrie! Paper looks good to me - the story is nice and clear. Happy with the itemized list. :)

Just noticed a couple of things on [84c7fdf](https://github.com/kazewong/flowMC/commit/84c7fdf554c724562f931c02bda3ec8f01edcbd7). Think, @matt-graham, left a few comments on your commit changes, but I'll give mine here. I believe that some of your references aren't appearing on the [compiled pdf](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05021/joss.05021/10.21105.joss.05021.pdf), perhaps due to missing an `@` symbol? Also, I spotted a few remaining typos:

## Intro
Paragraph 1:
- [ ] _prohitive_ -> _prohibitive_

Paragraph 2:
- [ ] _While multiple chains are **ran** using local-update Markov kernels to ...._ -> _While multiple chains are **run** using local-update Markov kernels to ..._

Itemised list:
- [ ] _Use of accelerators such as graphics processing **unites** (GPUs) and tensor processing **unites** (TPUs) are natively supported. The code also supports the use of multiple accelerators with SIMD parallelism._ -> _Use of accelerators such as graphics processing *units* (GPUs) and tensor processing *units* (TPUs) are natively supported. The code also supports the use of multiple accelerators with SIMD parallelism._ 
- [ ] _By default, just-in-time (JIT) compilations are used to further **acclerate** the sampling process._ -> _By default, just-in-time (JIT) compilations are used to further **accelerate** the sampling process._ 


## Statement of need:
- [ ] _The mathematical **detail** of the method are explained in [@Gabrie2021a]._ -> _The mathematical **details** of the method are explained in [@Gabrie2021a]._ 



- [ ] _While we provide a high-level API suitable for most **practitionners**, the code is also designed to be extensible._ -> _While we provide a high-level API suitable for most **practitioners**, the code is also designed to be extensible._

**Comment by marylou-gabrie** [comment]
Thank you very much for all your feedback. I believe all your remarks have been taken into accounts.

**Comment by Daniel-Dodd** [comment]
@marylou-gabrie nice one, really pleased with the end result, it reads well! Good job. :)
